server:
  port: 11001

spring:
  profiles:
    active: sharding-databases
  application:
    name: sharding-jdbc-demo

hzed:
  datasource:
    ip: 127.0.0.1
    username: root
    password: Lyson1234

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.sharding.demo.model
  global-config:
    db-config:
      id-type: ID_WORKER