spring:
  datasource:
    url: jdbc:mysql://${hzed.datasource.ip}:3306/oauth-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&serverTimezone=Hongkong
    username: ${hzed.datasource.username}
    password: ${hzed.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.oauth.model
  global-config:
    db-config:
      id-type: auto

hzed:
  oauth2:
    token:
      store:
        type: redis
  swagger:
    enabled: true
    title: 认证中心
    description: 认证中心接口文档
    version: 1.0
    base-package: com.central.oauth.controller
  security:
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: app