spring:
  datasource:
    url: jdbc:mysql://${zlt.datasource.ip}:3306/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
    username: ${zlt.datasource.username}
    password: ${zlt.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations:
    - classpath:/dao/*.xml
    - classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.common.model
  global-config:
    db-config:
      id-type: auto

zlt:
  swagger:
    enabled: true
    title: 商城后台中心
    description: 商城后台中心接口文档
    version: 1.0
    base-package: com.central.mall.admin.controller
  cache-manager:
    configs:
      - key: menu
        second: 300
      - key: user
        second: 1800
  #多租户配置
  tenant:
    enable: flase
    ignoreTables:
      - sys_user
      - sys_role_user
      - sys_role_menu