spring:
  datasource:
    url: jdbc:mysql://data-dev.hzed.net:3306/match1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${hzed.datasource.username}
    password: ${hzed.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath: /dao/*.xml
    - classpath: /mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.macro.mall.model
  global-config:
    db-config:
      id-type: auto

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4Fdba7nMTbrGiRTRKTjn # 访问身份验证中用到用户标识
    accessKeySecret: 0HDQM1H45NGQW109qTzjnpwoJJhmP6 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: hzed-dev2 # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://t01.hzed.com:177/fq-mall/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

mall:
  qmwalletApp:
    orderReceivUrl: http://10.10.20.156:7080/qmwallet-app/shopping/order/receive # 全民钱包购物借款订单url
  storage:
    tempdir: E:\tmp\

hzed:
  swagger:
    enabled: true
    title: 商城后台用户中心
    description: 商城后台用户中心接口文档
    version: 1.0
    base-package: com.macro.mall.controller
  cache-manager:
    configs:
      - key: menu
        second: 300
      - key: user
        second: 1800
  #多租户配置
  tenant:
    enable: false
    ignoreTables: